[package]

# Note: Semantic Versioning is used: https://semver.org/
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
version = "0.54.3"
=======
version = "0.41.0"
>>>>>>> 7f15ff0f612 (Updates torch to 2.7.0 with cuda 12.8 blackwell support (#2998))
=======
version = "0.41.1"
>>>>>>> b255b75263c (Fixes DCMotor clipping for negative power and adds actuator tests (#2300))
=======
version = "0.41.2"
>>>>>>> 1e930f1dbeb (Fixes isaaclab.scene.reset_to to properly accept None as valid argument (#2970))
=======
version = "0.41.3"
>>>>>>> 61a1114c2db (Fixes interval event resets and deprecation of `attach_yaw_only` flag (#2958))

# Description
title = "Isaac Lab framework for Robot Learning"
description="Extension providing main framework interfaces and abstractions for robot learning."
readme  = "docs/README.md"
repository = "https://github.com/isaac-sim/IsaacLab"
category = "robotics"
keywords = ["kit", "robotics", "learning", "ai"]

[python.pipapi]
requirements = [
    "numpy",
    "prettytable==3.3.0",
    "toml",
    "hidapi",
    "gymnasium==0.29.0",
    "trimesh",
    "websockets"
]

modules = [
    "numpy",
    "prettytable",
    "toml",
    "hid",
    "gymnasium",
    "trimesh",
    "websockets"
]

use_online_index=true

[core]
reloadable = false

[[python.module]]
name = "isaaclab"
